site_name: Guía para Estaciones de Referencia de Operación Continua de IGS
site_url: https://international-gnss-service.github.io/IGS_CORS_Guidelines/es/
repo_url: https://github.com/International-GNSS-Service/IGS_CORS_Guidelines
repo_name: IGS_CORS_Guidelines
copyright: Copyright &copy; 2026 International GNSS Service

docs_dir: '../../docs/es'
#site_dir: '../../generated/es' Este é gerado via GitHub Actions build -d

nav:
  - Introducción: index.md
  - Resumen: summary.md
  - Instalación y Funcionamiento:
    - Descripción General: establishment/index.md
    - Calidad de la Señal: establishment/signals.md
    - Estabilidad del Sitio: establishment/stability.md
    - Alimentación Eléctrica y Comunicaciones: establishment/power_comms.md
  - Equipamiento GNSS:
    - Descripción General: equipment/index.md
    - Receptor GNSS: equipment/receiver.md
    - Antena GNSS: equipment/antenna.md
    - Cable de Antena: equipment/cable.md
    - Sensores Meteorológicos: equipment/meteo_sensors.md
  - Datos y Metadatos:
    - Descripción General: data/index.md
    - Seguimiento de la Señal y Registro de Datos: data/recording.md
    - Convenciones de Nomenclatura de Archivos: data/filename.md
    - Calidad de los Datos: data/quality.md
    - Metadatos: data/metadata.md
    - Anuncios: data/announcements.md
  - Recursos:
    - Registro de Cambios: resources/changelog.md
    - Términos y Definiciones: resources/terms.md
    - Bibliografía: resources/references.md
    - Contribuciones: resources/contributions.md

theme:
  name: material
  language: es
  custom_dir: '../../overrides/' 
  logo: ../en/assets/images/igs_logo.png
  palette:
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro
  features:
    # - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - navigation.footer
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: false
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.tilde
  - admonition
  - def_list
  - toc:
      baselevel: 2
      permalink: true
  - meta
  - tables
  - footnotes
  - abbr
plugins:
  - include-markdown
  - search:
      lang: en
  - open-in-new-tab
  - git-revision-date-localized:
      enabled: true
      fallback_to_build_date: true
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/igsorg
      name: LinkedIn
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/igsorg
      name: X
    - icon: fontawesome/brands/youtube
      link: http://www.youtube.com/igsorg
      name: Youtube
    - icon: material/email
      link: "mailto:cb@igs.org"

  alternate:
    - name: English
      link: /IGS_CORS_Guidelines/en/ 
      lang: en
    - name: Deutsch
      link: /IGS_CORS_Guidelines/de/
      lang: de
    - name: Español
      link: /IGS_CORS_Guidelines/es/
      lang: es
    - name: Français
      link: /IGS_CORS_Guidelines/fr/
      lang: fr
    - name: Português
      link: /IGS_CORS_Guidelines/pt/
      lang: pt
    - name: 中国
      link: /IGS_CORS_Guidelines/cn/ 
      lang: zh
