site_name: Diretrizes IGS CORS
site_url: https://international-gnss-service.github.io/IGS_CORS_Guidelines/pt/
repo_url: https://github.com/International-GNSS-Service/IGS_CORS_Guidelines
repo_name: IGS_CORS_Guidelines
copyright: Copyright &copy; 2024 International GNSS Service

docs_dir: '../../docs/pt'
#site_dir: '../../generated/pt' Este é gerado via GitHub Actions build -d

nav:
  - Introdução: index.md
  - Sumário: summary.md
  - Estabelecimento e Operação:
    - Visão Geral: establishment/index.md
    - Qualidade do Sinal: establishment/signals.md
    - Estabilidade da Estação: establishment/stability.md
    - Energia e Comunicações: establishment/power_comms.md
  - Equipamento GNSS:
    - Visão Geral: equipment/index.md
    - Recetor GNSS: equipment/receiver.md
    - Antena GNSS: equipment/antenna.md
    - Cabo da Antena: equipment/cable.md
    - Sensores Meteorológicos: equipment/meteo_sensors.md
  - Dados e Metadados:
    - Visão Geral: data/index.md
    - Rastreamento de Sinais e Registo de Dados: data/recording.md
    - Convenções do Nome dos Ficheiros: data/filename.md
    - Qualidade dos Dados: data/quality.md
    - Metadados: data/metadata.md
    - Anúncios: data/announcements.md
  - Recursos:
    - Registo de Alterações: resources/changelog.md
    - Termos e Definições: resources/terms.md
    - Referências: resources/references.md
    - Contribuições: resources/contributions.md

theme:
  name: material
  language: pt
  custom_dir: '../../overrides/' 
  logo: ../en/assets/images/igs_logo.png
  palette:
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Mudar para modo claro
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Mudar para modo escuro
  features:
    # - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - navigation.footer
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: false
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.tilde
  - admonition
  - def_list
  - toc:
      baselevel: 2
      permalink: true
  - meta
  - tables
  - footnotes
  - abbr
plugins:
  - include-markdown
  - search:
      lang: en
  - open-in-new-tab
  - git-revision-date-localized:
      enabled: true
      fallback_to_build_date: true
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/igsorg
      name: LinkedIn
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/igsorg
      name: X
    - icon: fontawesome/brands/youtube
      link: http://www.youtube.com/igsorg
      name: Youtube
    - icon: material/email
      link: "mailto:cb@igs.org"

  alternate:
    - name: English
      link: /IGS_CORS_Guidelines/en/ 
      lang: en
    - name: Deutsch
      link: /IGS_CORS_Guidelines/de/
      lang: de
    - name: Français
      link: /IGS_CORS_Guidelines/fr/
      lang: fr
    - name: 中国
      link: /IGS_CORS_Guidelines/cn/ 
      lang: zh
    - name: Português
      link: /IGS_CORS_Guidelines/pt/
      lang: pt
    - name: Español
      link: /IGS_CORS_Guidelines/es/
      lang: es
