site_name: Directives pour les Stations GNSS Permanentes de l’IGS
site_url: https://international-gnss-service.github.io/IGS_CORS_Guidelines/fr/
repo_url: https://github.com/International-GNSS-Service/IGS_CORS_Guidelines
repo_name: IGS_CORS_Guidelines
copyright: Copyright &copy; 2026 International GNSS Service

docs_dir: '../../docs/fr'
#site_dir: '../../generated/fr' 

nav:
  - Introduction: index.md
  - Résumé des Directives pour les CORS IGS: summary.md
  - Installation et Opération des Stations GNSS Permanentes de l’IGS:
    - Vue d'Ensemble: establishment/index.md
    - Qualité du Signal: establishment/signals.md
    - Stabilité du Site: establishment/stability.md
    - Alimentation et Télécommunications: establishment/power_comms.md
  - Équipements GNSS:
    - Vue d'Ensemble: equipment/index.md
    - Récepteur GNSS: equipment/receiver.md
    - Antenne GNSS: equipment/antenna.md
    - Câble d’Antenne: equipment/cable.md
    - Capteurs Météorologiques: equipment/meteo_sensors.md
  - Données et Métadonnées:
    - Vue d'Ensemble: data/index.md
    - Suivi de Signal et Enregistrement de Données: data/recording.md
    - Dénomination des Fichiers: data/filename.md
    - Qualité des Données: data/quality.md
    - Métadonnées: data/metadata.md
    - Annonces: data/announcements.md
  - Ressources:
    - Journal des Modifications: resources/changelog.md
    - Termes et Définitions: resources/terms.md
    - Références: resources/references.md
    - Contributions: resources/contributions.md

theme:
  name: material
  language: fr
  custom_dir: '../../overrides/' 
  logo: ../en/assets/images/igs_logo.png
  palette:
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Passer au mode clair
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Passer au mode sombre
  features:
    # - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - navigation.footer
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: false
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.tilde
  - admonition
  - def_list
  - toc:
      baselevel: 2
      permalink: true
  - meta
  - tables
  - footnotes
  - abbr
plugins:
  - include-markdown
  - search:
      lang: en
  - open-in-new-tab
  - git-revision-date-localized:
      enabled: true
      fallback_to_build_date: true
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/igsorg
      name: LinkedIn
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/igsorg
      name: X
    - icon: fontawesome/brands/youtube
      link: http://www.youtube.com/igsorg
      name: Youtube
    - icon: material/email
      link: "mailto:cb@igs.org"

  alternate:
    - name: English
      link: /IGS_CORS_Guidelines/en/ 
      lang: en
    - name: Deutsch
      link: /IGS_CORS_Guidelines/de/
      lang: de
    - name: Français
      link: /IGS_CORS_Guidelines/fr/
      lang: fr
    - name: 中国
      link: /IGS_CORS_Guidelines/cn/ 
      lang: zh
    - name: Português
      link: /IGS_CORS_Guidelines/pt/
      lang: pt
    - name: Español
      link: /IGS_CORS_Guidelines/es/
      lang: es
